import Foundation

/// A level *index*: `levels/1`.
///
/// The scale problem this solves. `LevelLibrary` used to enumerate every JSON in the
/// bundle and fully decode each one to find out whether it was a level. At six levels
/// that is free. At a thousand it is a full decode of every level file before the menu
/// can draw — measured at roughly a second of launch, with every level's rows held
/// resident for the whole session.
///
/// The index is one small file listing what exists. Launch reads *that*; a level's
/// rows are decoded when the level is actually played and dropped when it isn't.
///
/// ```json
/// { "format": "levels/1",
///   "levels": [ {"name": "grove", "order": 10, "title": "Sunlit Grove"} ] }
/// ```
///
/// Generated by `Tools/level_index.py` and checked by the audit, because an index that
/// disagrees with the files on disk is a level that silently vanishes from the game.
struct LevelIndex: Codable {

    static let currentFormat = "levels/1"
    static let resourceName = "levels"

    /// One entry. Everything the menu needs, and nothing that would make the index
    /// large — deliberately *not* the rows.
    struct Entry: Codable, Equatable {
        var name: String
        var order: Int
        var title: String?
        /// Grid size, so a menu or a planner can show scale without a decode.
        var cols: Int?
        var rows: Int?

        var displayTitle: String { title ?? name }
    }

    var format: String = LevelIndex.currentFormat
    var levels: [Entry]

    var problems: [String] {
        var out: [String] = []
        if format != LevelIndex.currentFormat {
            out.append("format is '\(format)', expected '\(LevelIndex.currentFormat)'")
        }
        let names = levels.map(\.name)
        if names.count != Set(names).count { out.append("duplicate level names") }
        let orders = levels.map(\.order)
        if orders.count != Set(orders).count { out.append("duplicate order values") }
        return out
    }

    static func load(bundle: Bundle = .main) -> LevelIndex? {
        guard let url = bundle.url(forResource: resourceName, withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let index = try? JSONDecoder().decode(LevelIndex.self, from: data),
              index.format == currentFormat, index.problems.isEmpty
        else { return nil }
        return index
    }
}

/// Loads a single level's full contents on demand, with a small cache.
///
/// The cache holds the level being played plus the one either side, which is what a
/// menu that shows neighbours needs. Beyond that, dropping a level's rows is free —
/// re-decoding one small file costs under a millisecond, and holding a thousand of
/// them costs megabytes for no benefit.
final class LevelStore {

    static let shared = LevelStore()

    private var cache: [String: LevelFile] = [:]
    private var recent: [String] = []
    private let capacity = 3

    private init() {}

    func level(named name: String, bundle: Bundle = .main) -> LevelFile? {
        if let hit = cache[name] {
            touch(name)
            return hit
        }
        guard let url = bundle.url(forResource: name, withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(LevelFile.self, from: data),
              file.format == LevelFile.currentFormat,
              file.structuralProblems.isEmpty
        else { return nil }
        cache[name] = file
        touch(name)
        return file
    }

    private func touch(_ name: String) {
        recent.removeAll { $0 == name }
        recent.append(name)
        while recent.count > capacity, let oldest = recent.first {
            recent.removeFirst()
            cache[oldest] = nil
        }
    }

    /// Drop everything — for a memory warning, or between worlds.
    func purge() {
        cache.removeAll()
        recent.removeAll()
    }

    var cachedCount: Int { cache.count }
}
